// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBepy_4riQ46CkGfQ60WSDed5bp4QLv9Po',
    appId: '1:604698991884:web:39cf2c61e9f3b49099fd29',
    messagingSenderId: '604698991884',
    projectId: 'cook-with-nhee',
    authDomain: 'cook-with-nhee.firebaseapp.com',
    storageBucket: 'cook-with-nhee.firebasestorage.app',
    measurementId: 'G-QFK5V0WKS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDilDMiQ6DVKLIUiCAvVWjj7rVy4KNw5SI',
    appId: '1:604698991884:android:e7a0ead58457985699fd29',
    messagingSenderId: '604698991884',
    projectId: 'cook-with-nhee',
    storageBucket: 'cook-with-nhee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8rfzSVblEJKvxxPssI94eWhTeuGR04Hc',
    appId: '1:604698991884:ios:be441ed87fb32f1c99fd29',
    messagingSenderId: '604698991884',
    projectId: 'cook-with-nhee',
    storageBucket: 'cook-with-nhee.firebasestorage.app',
    iosBundleId: 'com.penz.cookWithNhee',
  );
}
